### PR TITLE
Update Ember version to 2.1.0

### PR DESCRIPTION
**Pull request by leandrost**

### CODE REVIEW

**Comment by leandrost** [comment]
@tauil works on my machine :smile:

**Comment by tauil** [comment]
:+1:

**Comment by vagnerzampieri** [comment]
tests?? :P

**Comment by leandrost** [comment]
@vagnerzampieri abre um PR aew :smile:

**Comment by vagnerzampieri** [comment]
@leandrost agora tem que abrir, o @tauil fechou :P

**Comment by tauil** [comment]
the tests should be written in another PR, not this. This is just a framework version update.

**Comment by vagnerzampieri** [comment]
He implemented more things.

**Comment by wpolicarpo** [comment]
popcorn

**Comment by vagnerzampieri** [comment]
HAHAHAHAHA

**Comment by leandrost** [comment]
I did NOT implement more things, i just took care of deprecation warnings... :smile_cat:

**Pull request merged**
